version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:6.0
    volumes:
    - ./scripts/rs-init.sh:/scripts/rs-init.sh
    - ./scripts/init.js:/scripts/init.js
    - mongodb_cluster_mongo1_data:/data/db
    environment: &mongoServerEnvs
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    configs:
      - mongodb-keyfile
    networks:
    - mongo-network
    ports:
    - 27017:27017
    depends_on:
    - mongo2
    - mongo3
    links:
    - mongo2
    - mongo3
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--keyFile", "mongodb-keyfile"]

  mongo2:
    container_name: mongo2
    image: mongo:6.0
    volumes:
      - mongodb_cluster_mongo2_data:/data/db
    environment:
      <<: *mongoServerEnvs
    configs:
      - mongodb-keyfile
    networks:
    - mongo-network
    ports:
    - 27018:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--keyFile", "mongodb-keyfile"]

  mongo3:
    container_name: mongo3
    image: mongo:6.0
    volumes:
      - mongodb_cluster_mongo3_data:/data/db
    environment:
      <<: *mongoServerEnvs
    configs:
      - mongodb-keyfile
    networks:
    - mongo-network
    ports:
    - 27019:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--keyFile", "mongodb-keyfile"]

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1
    networks:
    - mongo-network
    ports:
    - 8081:8081
    environment:
      PORT: "8081"
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo1:27017,mongo2:27017,mongo3:27017/admin?authSource=admin&replicaSet=dbrs
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example2
    depends_on:
    - mongo1
    restart: always

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb_cluster_mongo1_data:
  mongodb_cluster_mongo2_data:
  mongodb_cluster_mongo3_data:

configs:
  mongodb-keyfile:
    file: ./configs/mongodb-keyfile
